version: '3.8'

services:
    php:
        build:
            context: .
            dockerfile: .docker/php/Dockerfile
        container_name: php
        volumes:
            - .:/var/www
        networks:
            - to-backend

    nginx:
        image: nginx:alpine
        container_name: nginx
        ports:
            - ${DOCKER_OUTER_PORT_NGINX}:80
        volumes:
            - .:/var/www
            - ./.docker/nginx/conf.d:/etc/nginx/conf.d/
        networks:
            - to-backend

    postgres:
        image: postgres
        container_name: postgres
        environment:
            POSTGRES_DB: hackathon
            POSTGRES_USER: hackathon
            POSTGRES_PASSWORD: hackathon
        volumes:
            - pgsql-data:/var/lib/postgresql/data
        ports:
            - ${DOCKER_OUTER_PORT_POSTGRES}:5432
        networks:
            - to-backend

networks:
    to-backend:
        driver: bridge

volumes:
    pgsql-data:
        driver: local
